/**
 * Constants for ComparisonHero component
 */

export const NAV_ITEMS = [
  "Perfil General",
  "Experiencia Política",
  "Experiencia Profesional",
  "Ideología Política",
  "Propuestas Principales",
  /*   "Coherencia con el Plan", */
  "Controversias",
  /*   "Transparencia",
  "Competencias personales",
  "Percepción Pública",
  "Innovación y Visión", */
  "Proyectos de Ley",
] as const;

export interface Candidate {
  id: string;
  src: string;
  name: string; // Full name to display (also used as alt text)
  dataKey: string; // Key to lookup in candidatesData
  // Image dimensions per breakpoint (mobile/default, sm, md, lg)
  imageWidth?: number; // Default/mobile width (grid 5x2)
  imageHeight?: number; // Default/mobile height (grid 5x2)
  imageWidthSm?: number; // SM breakpoint width
  imageHeightSm?: number; // SM breakpoint height
  imageWidthMd?: number; // MD breakpoint width (grid 2 cols)
  imageHeightMd?: number; // MD breakpoint height (grid 2 cols)
  imageWidthLg?: number; // LG+ breakpoint width
  imageHeightLg?: number; // LG+ breakpoint height
  // Offset per breakpoint
  offsetY?: number; // Y-axis offset default (default: 16)
  offsetX?: number; // X-axis offset default (default: 0)
  offsetYSm?: number; // Y-axis offset for SM
  offsetXSm?: number; // X-axis offset for SM
  offsetYMd?: number; // Y-axis offset for MD
  offsetXMd?: number; // X-axis offset for MD
  // Image filters (CSS filter values)
  brightness?: number; // Exposición/luces (default: 1, >1 más brillante, <1 más oscuro)
  contrast?: number; // Contraste (default: 1, >1 más contraste)
  saturate?: number; // Saturación (default: 1, >1 más saturado, <1 desaturado)
  sepia?: number; // Temperatura/calidez (default: 0, 0.1-0.4 = cálido, 0 = neutral)
  shadows?: number; // Sombras (default: 1, >1 = levanta sombras, <1 = oscurece sombras)
}

export const CANDIDATES: Candidate[] = [
  {
    id: "keiko",
    src: "/candidatos/keiko-fujimori.webp",
    name: "Keiko Fujimori",
    dataKey: "keiko",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "lopez",
    src: "/candidatos/rafael-lopez-aliaga.webp",
    name: "Rafael López Aliaga",
    dataKey: "lopez",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "cesar-acuna",
    src: "/candidatos/cesar-acuna.webp",
    name: "César Acuña",
    dataKey: "cesar-acuna",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 16,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "vladimir-cerron",
    src: "/candidatos/vladimir-cerron.webp",
    name: "Vladimir Cerrón",
    dataKey: "vladimir-cerron",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "alfonso-lopez-chau",
    src: "/candidatos/alfonso-lopez-chau.webp",
    name: "Alfonso López Chau",
    dataKey: "alfonso-lopez-chau",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "roberto-sanchez",
    src: "/candidatos/roberto-sanchez.webp",
    name: "Roberto Sánchez",
    dataKey: "roberto-sanchez",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "mario-vizcarra",
    src: "/candidatos/mario-vizcarra.webp",
    name: "Mario Vizcarra",
    dataKey: "mario-vizcarra",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "enrique-valderrama",
    src: "/candidatos/enrique-valderrama.webp",
    name: "Enrique Valderrama",
    dataKey: "enrique-valderrama",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "yonhy-lescano",
    src: "/candidatos/yonhy-lescano.webp",
    name: "Yonhy Lescano",
    dataKey: "yonhy-lescano",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "fernando-olivera",
    src: "/candidatos/fernando-olivera.webp",
    name: "Fernando Olivera",
    dataKey: "fernando-olivera",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "george-forsyth",
    src: "/candidatos/george-forsyth.webp",
    name: "George Forsyth",
    dataKey: "george-forsyth",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
  {
    id: "carlos-espa",
    src: "/candidatos/carlos-espa.webp",
    name: "Carlos Espá",
    dataKey: "carlos-espa",
    imageWidth: 100,
    imageHeight: 100,
    imageWidthSm: 110,
    imageHeightSm: 110,
    imageWidthMd: 100,
    imageHeightMd: 100,
    imageWidthLg: 125,
    imageHeightLg: 125,
    offsetY: 16,
    offsetYSm: 14,
    offsetYMd: 14,
    brightness: 1,
    contrast: 1,
    saturate: 1,
    sepia: 0,
    shadows: 1,
  },
];

export const SELECTION_COLORS = {
  first: "#FF2727",
  second: "#3E4692",
} as const;

// Section IDs (derived from NAV_ITEMS without spaces)
export const SECTION_IDS = NAV_ITEMS.map((item) =>
  item.replace(/\s+/g, "")
) as readonly string[];
